name: happy_farm
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  cached_network_image: ^3.2.3
  intl: ^0.18.0
  shimmer: ^2.0.0
  lottie: ^3.0.0
  razorpay_flutter: ^1.3.5
  url_launcher: ^6.3.1
  icons_plus: ^5.0.0
  font_awesome_flutter: ^10.8.0
  path: 1.9.0
  image_cropper: ^8.1.0
  image_picker: ^1.1.2
  crop_your_image: ^2.0.0
  location: ^5.0.0
  geocoding: ^4.0.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - .env

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
